"""srcport-framework — Python host + module plugins (v2.2).

Opinionated application layer on :mod:`srcport_substrate`. The kernel never
loads plugins or calls presentation / storage hooks — only a :class:`Host` does.
"""

from .cut import (
    SEED_INPUT_PREFIX,
    AssemblyCut,
    SeedSpec,
    SkippedNode,
    is_seed_input_name,
    materialize_cut,
    merge_inputs,
    resolve_kept_nodes,
    seed_input_name,
    seeds_from_run,
    validate_seeds_present,
)
from .errors import FrameworkError
from .host import Host, UiPersist
from .memo import (
    MemoNodes,
    MemoPlan,
    MemoRecord,
    MemoStore,
    MemoryMemo,
    build_record,
    input_fingerprint_map,
    memo_key,
    record_to_named_outputs,
)
from .plugin import ModulePlugin, PortBody, StepContext, StepOutput
from .policy import (
    DEFAULT_CONCURRENCY,
    DriveAfter,
    DrivePlan,
    FiringPlan,
    FrameworkPolicy,
    NodePlan,
    RunMode,
)
from .presentation import (
    CONTRACT_STEP_CACHED,
    CONTRACT_STEP_FINAL,
    CONTRACT_STEP_INIT,
    CONTRACT_STEP_PROGRESS,
    CONTRACT_STEP_SKIPPED,
    Presentation,
    PresentationStatus,
    StepEvent,
    StepResult,
    StepStage,
)
from .storage import (
    STEP_LOG_TABLE,
    ColumnDef,
    ColumnType,
    MemoryStorage,
    QualifiedTable,
    StorageBackend,
    StorageMode,
    StoragePlan,
    StorageRetention,
    StoreRow,
    StoreValue,
    StoreWrite,
    TableSchema,
    WriteMode,
    inject_identity,
    qualify_table,
    store_row,
)

__version__ = "2.1.0"

__all__ = [
    "AssemblyCut",
    "ColumnDef",
    "ColumnType",
    "CONTRACT_STEP_CACHED",
    "CONTRACT_STEP_FINAL",
    "CONTRACT_STEP_INIT",
    "CONTRACT_STEP_PROGRESS",
    "CONTRACT_STEP_SKIPPED",
    "DEFAULT_CONCURRENCY",
    "DriveAfter",
    "DrivePlan",
    "FiringPlan",
    "FrameworkError",
    "FrameworkPolicy",
    "Host",
    "MemoNodes",
    "MemoPlan",
    "MemoRecord",
    "MemoStore",
    "MemoryMemo",
    "MemoryStorage",
    "ModulePlugin",
    "NodePlan",
    "PortBody",
    "Presentation",
    "PresentationStatus",
    "QualifiedTable",
    "RunMode",
    "SEED_INPUT_PREFIX",
    "SeedSpec",
    "SkippedNode",
    "STEP_LOG_TABLE",
    "StepContext",
    "StepEvent",
    "StepOutput",
    "StepResult",
    "StepStage",
    "StorageBackend",
    "StorageMode",
    "StoragePlan",
    "StorageRetention",
    "StoreRow",
    "StoreValue",
    "StoreWrite",
    "TableSchema",
    "UiPersist",
    "WriteMode",
    "build_record",
    "inject_identity",
    "input_fingerprint_map",
    "is_seed_input_name",
    "materialize_cut",
    "memo_key",
    "merge_inputs",
    "qualify_table",
    "record_to_named_outputs",
    "resolve_kept_nodes",
    "seed_input_name",
    "seeds_from_run",
    "store_row",
    "validate_seeds_present",
]
