"""srcport-substrate — Python SDK (v1.0.0, in-process).

One pluggable core: seven primitives (Module · Artifact · Contract · Event ·
Ledger · Registry · Run) and one Kernel ABI, conformant to SPEC.md.
:class:`MemoryKernel` implements :class:`KernelApi` in-process. **Durability
lives in Modules, not the core** — the in-memory kernel is one backend, not the
authority.
"""

from ._kernel import (
    SUBSCRIBER_BUFFER,
    BlobIntegrity,
    Conflict,
    Invalid,
    KernelApi,
    KernelError,
    MemoryKernel,
    NotFound,
    RunClosed,
)
from ._types import (
    AppendRequest,
    Artifact,
    ArtifactRef,
    Assembly,
    AssemblyNode,
    Binding,
    BlobData,
    BlobRef,
    Capability,
    ClaimRequest,
    Contract,
    Derivation,
    DerivationList,
    Error,
    ErrorCode,
    Event,
    GetBlobRequest,
    HasBlobRequest,
    HasBlobResponse,
    LedgerEntry,
    Lifecycle,
    Limits,
    MAX_INLINE_ARTIFACT_BYTES,
    ModuleManifest,
    NamedArtifact,
    NodeOutput,
    ObjectRef,
    Port,
    PublishAck,
    PutBlobRequest,
    RegisterAck,
    RegistrySnapshot,
    RequestContext,
    Run,
    RunRef,
    RunRequest,
    RunState,
    SnapshotRequest,
    Subscription,
    WorkItem,
    artifact_content,
    artifact_id,
    artifact_id_of,
    blob_id,
    contract_digest,
    contract_digest_of,
    has_external_object,
    is_contract_placeholder,
    object_ref_bytes,
    verify_chain,
)

__version__ = "1.0.0"

__all__ = [
    "MemoryKernel",
    "KernelApi",
    "KernelError",
    "NotFound",
    "Invalid",
    "Conflict",
    "RunClosed",
    "BlobIntegrity",
    "SUBSCRIBER_BUFFER",
    "Lifecycle",
    "RunState",
    "ErrorCode",
    "Port",
    "Capability",
    "ModuleManifest",
    "BlobRef",
    "ObjectRef",
    "Artifact",
    "ArtifactRef",
    "PutBlobRequest",
    "GetBlobRequest",
    "BlobData",
    "HasBlobRequest",
    "HasBlobResponse",
    "Contract",
    "Event",
    "Subscription",
    "LedgerEntry",
    "RegistrySnapshot",
    "RegisterAck",
    "PublishAck",
    "AppendRequest",
    "NamedArtifact",
    "AssemblyNode",
    "Binding",
    "NodeOutput",
    "Limits",
    "Assembly",
    "RunRequest",
    "Run",
    "RunRef",
    "ClaimRequest",
    "WorkItem",
    "Derivation",
    "DerivationList",
    "RequestContext",
    "Error",
    "SnapshotRequest",
    "MAX_INLINE_ARTIFACT_BYTES",
    "artifact_id",
    "artifact_id_of",
    "artifact_content",
    "blob_id",
    "object_ref_bytes",
    "has_external_object",
    "contract_digest",
    "contract_digest_of",
    "is_contract_placeholder",
    "verify_chain",
    "__version__",
]
