"""srcport-substrate — Python SDK (v0.1, in-process).

One pluggable core: eight primitives (Module · Artifact · Contract · Event ·
Ledger · Gate · Registry · Run) and one Kernel ABI, conformant to SPEC.md. The
:class:`Kernel` methods mirror the ``service Kernel`` RPCs in substrate.proto.
"""

from ._kernel import (
    Conflict,
    GateBlocked,
    Invalid,
    Kernel,
    KernelError,
    NotADecision,
    NotFound,
    RunClosed,
)
from ._types import (
    AppendRequest,
    Artifact,
    ArtifactRef,
    Assembly,
    AssemblyNode,
    Binding,
    Capability,
    ClaimRequest,
    Contract,
    Decision,
    Derivation,
    DerivationList,
    Event,
    GateDecision,
    GateRequest,
    GateTicket,
    LedgerEntry,
    Lifecycle,
    Limits,
    ModuleManifest,
    NamedArtifact,
    NodeOutput,
    Port,
    PublishAck,
    RegisterAck,
    RegistrySnapshot,
    Run,
    RunRef,
    RunRequest,
    RunState,
    Subscription,
    WorkItem,
    artifact_id,
    verify_chain,
)

__version__ = "0.1.1"

__all__ = [
    "Kernel",
    "KernelError",
    "NotFound",
    "NotADecision",
    "GateBlocked",
    "Invalid",
    "Conflict",
    "RunClosed",
    "Lifecycle",
    "Decision",
    "RunState",
    "Port",
    "Capability",
    "ModuleManifest",
    "Artifact",
    "ArtifactRef",
    "Contract",
    "Event",
    "Subscription",
    "LedgerEntry",
    "GateRequest",
    "GateDecision",
    "GateTicket",
    "RegistrySnapshot",
    "RegisterAck",
    "PublishAck",
    "AppendRequest",
    "NamedArtifact",
    "AssemblyNode",
    "Binding",
    "NodeOutput",
    "Limits",
    "Assembly",
    "RunRequest",
    "Run",
    "RunRef",
    "ClaimRequest",
    "WorkItem",
    "Derivation",
    "DerivationList",
    "artifact_id",
    "verify_chain",
    "__version__",
]
